package dev.splitdeploy

import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings

/**
 * Settings plugin (id: 'ftc.splitdeploy').
 *
 * Apply this in settings.gradle of a stock FtcRobotController project:
 *
 *   pluginManagement {
 *       repositories { gradlePluginPortal(); google(); mavenCentral() } // + your plugin repo
 *   }
 *   plugins { id 'ftc.splitdeploy' version '<version>' }
 *
 * and remove the line `apply from: '../build.common.gradle'` from
 * TeamCode/build.gradle. That's the whole installation.
 *
 * What it does:
 *  - Generates and includes a synthetic ':FtcBase' application module under
 *    .splitdeploy/ (fully generated, self-gitignored). This becomes the base
 *    APK: the FtcRobotController activity, the FTC SDK, and all libraries.
 *  - Configures ':TeamCode' as a dynamic-feature module, so team code builds
 *    into a small split APK instead.
 *  - Registers deploy tasks:
 *      deployTeamCode  — build + partially install ONLY the TeamCode split,
 *                        then restart the RC app (a few seconds end-to-end)
 *      installFullApp  — full base+split install (first time / SDK or library
 *                        changes)
 *      splitDeployDoctor — read-only device/base/duplicate-class preflight
 *      rollbackTeamCode — restore the split backed up before the last deploy
 *      initSplitDeploy — writes Android Studio run configurations (.run/)
 */
class SplitDeploySettingsPlugin implements Plugin<Settings> {

    private static final String BASE_MANIFEST = '''\
<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by the ftc.splitdeploy Gradle plugin - do not edit.
     The real application manifest (activities, permissions, ...) is merged in
     from the FtcRobotController library module. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application/>
</manifest>
'''

    @Override
    void apply(Settings settings) {
        // Generate the synthetic base application module.
        File baseDir = new File(settings.rootDir, '.splitdeploy/FtcBase')
        File mainDir = new File(baseDir, 'src/main')
        mainDir.mkdirs()
        writeIfChanged(new File(settings.rootDir, '.splitdeploy/.gitignore'), '*\n')
        writeIfChanged(new File(mainDir, 'AndroidManifest.xml'), BASE_MANIFEST)

        settings.include(':FtcBase')
        settings.project(':FtcBase').projectDir = baseDir

        settings.gradle.beforeProject { project ->
            // Every Android module gets AGP's raw install/uninstall tasks;
            // block them so the plugin tasks are the only device entry points.
            UnsafeDeviceTaskGuard.guard(project)
            if (project.path == ':FtcBase') {
                project.pluginManager.apply(FtcBasePlugin)
            } else if (project.path == ':TeamCode') {
                project.pluginManager.apply(TeamCodeFeaturePlugin)
            }
        }
    }

    private static void writeIfChanged(File file, String content) {
        if (!file.exists() || file.getText('UTF-8') != content) {
            file.parentFile.mkdirs()
            file.setText(content, 'UTF-8')
        }
    }
}
